### ISSUE TITLE
[Question] Is the Formations series of mods serverside?

### ISSUE THREAD

**Issue by VeggeieDude** [SuperMartijn642/FormationsOverworld#1]
**Question**
...Can I install the Formations mods on serverside only?

**Comment by SuperMartijn642** [comment]
Technically yes, however now that you mention it, I don't think I set it up for that. Currently the server will reject clients without the mods.
I will see if I can make it ignore that.

**Comment by SuperMartijn642** [comment]
Nevermind, since Formations doesn't add anything to any networked registries, you can join already server without having the mod installed on the client. So yeah, you can install the Formations mods only on the server-side.
