### ISSUE TITLE
[Question] Is it possible to disable structures?

### ISSUE THREAD

**Issue by katubug** [SuperMartijn642/FormationsOverworld#3]
**Question**
I'm a modpack maker looking to pare down the number of structures in the world. Is there a way to disable certain structures, such as through a datapack?

**Comment by SuperMartijn642** [comment]
You can indeed disable structures using a datapack, just like you'd for vanilla. You can find the locations of the structure files here: https://github.com/SuperMartijn642/FormationsOverworld/tree/master/src/generated/resources/data/formationsoverworld/worldgen/structure_set

**Comment by katubug** [comment]
Awesome, thank you very much!
